### ISSUE TITLE
Jetty version upgrade

### ISSUE THREAD

**Issue by cosmin-marginean** [cometd/cometd#672]
Hi guys

There are some issues in relation to the Jetty version that is currently used as a dependency in CometD (9.2.18.v20160721). It seems that `ServletPathSpec` is one of the culprits. This class inherits from `PathSpec` which has been moved by Jetty into the `org.eclipse.jetty.http.pathmap` package (rather than the previous `org.eclipse.jetty.websocket.server.pathmap`)

This causes an inability to run CometD on more recent versions of Jetty because of a

```
java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.pathmap.PathSpec
```

**Comment by sbordet** [comment]
I'm not sure I understand. You refer to 2 Jetty classes so even if something changed, they should be in sync with each other, provided you don't mix Jetty versions.

What CometD version are you using ?

Full stack trace ?

**Comment by mrossi975** [comment]
hi,
I have also experienced the same problem attempting to use CometD 3.0.9 with Jetty 9.3.X.

Basically CometD refers directly to the old name of those classes which have been since refactored and moved elsewhere.

I have resolved by disabling WebSockets as it's not critical for my application.

thanks,
Michele

**Comment by cosmin-marginean** [comment]
Hi 

Sorry, so the complete context is that we have a container running latest Jetty 9.3.10.v20160621 and unfortunately we're stuck with that. CometD Java however is using 9.2.18.v20160721.

Between 9.2.18.v20160721 and 9.3.10.v20160621 there have been some refactorings within the Jetty library, and trying to use CometD with 9.3.10.v20160621. Below is the complete stacktrace

```
! Suppressed: java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.pathmap.PathSpec
! 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
! 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! 	... 52 common frames omitted
! Causing: java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/server/pathmap/PathSpec
! 	at java.lang.Class.getDeclaredConstructors0(Native Method)
! 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
! 	at java.lang.Class.getConstructor0(Class.java:3075)
! 	at java.lang.Class.getConstructor(Class.java:1825)
! 	at org.cometd.server.BayeuxServerImpl.newServerTransport(BayeuxServerImpl.java:317)
! 	at org.cometd.server.BayeuxServerImpl.initializeServerTransports(BayeuxServerImpl.java:229)
! 	at org.cometd.server.BayeuxServerImpl.doStart(BayeuxServerImpl.java:128)
! 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! 	at org.cometd.server.CometDServlet.init(CometDServlet.java:67)
! 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
! 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
! 	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
! 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
```

So what happens is that`JettyWebSocketTransport` is using `org.eclipse.jetty.websocket.server.pathmap.ServletPathSpec` which is now deprecated https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/pathmap/ServletPathSpec.java

Now that wouldn't be the end of the world normally, but the problem is that this class was not only deprecated but also refactored from

```
public class ServletPathSpec extends PathSpec
````
(where the `PathSpec` was actually `org.eclipse.jetty.websocket.server.pathmap.PathSpec`)
```

to 

```
public class ServletPathSpec extends org.eclipse.jetty.http.pathmap.ServletPathSpec
```
which is
```
public class ServletPathSpec extends PathSpec
```
(where `PathSpec` here is now `org.eclipse.jetty.http.pathmap.PathSpec` instead)

So at runtime when an instance of `JettyWebSocketTransport` is created, an instance of `ServletPathSpec` is requested as part of initialisation, which in turn will trigger a classloader lookup, with the expectation to find a `org.eclipse.jetty.websocket.server.pathmap.PathSpec` which doesn't exist anymore.

```
Causing: java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/server/pathmap/PathSpec
```

**Comment by sbordet** [comment]
@cosmin-marginean this problem existed since December last year, when the `PathSpec` refactoring landed in Jetty 9.3.x. I don't think it's related to Jetty 9.2.18. Can you confirm that ?

We filed eclipse/jetty.project#780, which has already been fixed.

Would you be able to try your CometD version (I presume 3.0.9 ?) against the latest Jetty 9.3.12-SNAPSHOT ?

**Comment by cosmin-marginean** [comment]
@sbordet Ah, I haven't tested against the Snapshot build. In that case it should work with the next release of Jetty.

I've only tested with 9.3.10.v20160621 where it does break because that version does contain the refactoring. 

> I don't think it's related to Jetty 9.2.18
No, that is the version that CometD references and expects (and where the refactoring doesn't exist yet) so running it with 9.3.10.v20160621 where the PathSpec refactoring does exist, will cause it to break.

Hope this helps. Thanks for raising it with the Jetty community.

**Comment by sbordet** [comment]
Let us know if you can test and verify the fix works.

**Comment by sbordet** [comment]
@cosmin-marginean, @mrossi975 were you guys able to test this and confirm that it's working fine with Jetty 9.3.12+ ?

**Comment by cosmin-marginean** [comment]
We're running a custom build of cometd with 9.3.10.v20160621 (which means no upgrades, etc) but it was the only way out of this.

**Comment by sbordet** [comment]
@cosmin-marginean this issue is supposed to be fixed in 9.3.12+. Have you tried that ?

**Comment by cosmin-marginean** [comment]
I haven't yet I'm afraid, no.

**Comment by cosmin-marginean** [comment]
Just as an update, I am now running with jetty `9.3.14.v20161028` and a CometD build from the maven repo (3.0.10 from here https://mvnrepository.com/artifact/org.cometd.java/cometd-java-server) and problems with jetty API compatibility still occur.

For the moment we're still a) cloning cometd, b) modifying the main pom.xml to point to modern jetty c) rebuilding cometd and using the snapshot version.

We'll have to address this though, and have it work in a more structured manner and not use snapshot code. While it's doable it's rather laborious and divergent from the release process. But it's the only option unless the cometD community is willing to explore upgrading they jetty dependency.

**Comment by sbordet** [comment]
@cosmin-marginean,

If you are using Maven to build your application, it should be enough that you define the Jetty version you want in your application `pom.xml` and then work out the various CometD dependencies (via `mvn dependency:tree`) and explicitly add those Jetty dependency to your application `pom.xml`.
That should override all Jetty 9.2.x dependencies that CometD may pull transitively, and use the Jetty 9.3.x that you define explicitly in your application `pom.xml`.

If that does not work, or you use some other dependency mechanism, then you have to give more details. With the issue you reported (eclipse/jetty.project#780) fixed, I think this is only a matter of precise dependency declaration.

Would you be able to try CometD 3.1.0-RC1 ?

**Comment by cosmin-marginean** [comment]
Thanks @sbordet for the prompt and detailed reply.
I can confirm that this now works with 3.1.0-RC1 so will switch to that in our build system once we have it on maven central.
Many thanks again for looking into this.
